### ISSUE TITLE
`attributes` not `attrs` for V1

### ISSUE THREAD

**Issue by Aloento** [stackmon/status-dashboard-v3#10]
https://github.com/stackmon/status-dashboard-v3/blob/d2a000dae8be50543ea1438912abb7e4206a178b/openapi.yaml#L407

```yaml
definitions: 
  attributes: 
    type: array
    items: 
      type: object
      properties: 
        name: 
          type: string
        value: 
          type: string
  id: 
    type: number
  incidents: 
    type: array
    items: 
      type: object
      properties: 
        end_date: 
          type: string
        id: 
          type: number
        impact: 
          type: number
        start_date: 
          type: string
        text: 
          type: string
        updates: 
          type: array
          items: 
            type: object
            properties: 
              status: 
                type: string
              text: 
                type: string
              timestamp: 
                type: string
  name: 
    type: string
```

example

```json
{
  "attributes": [
    {
      "name": "category",
      "value": "Network"
    },
    {
      "name": "region",
      "value": "EU-NL"
    },
    {
      "name": "type",
      "value": "vpn"
    }
  ],
  "id": 283,
  "incidents": [
    {
      "end_date": "2024-03-26 08:38",
      "id": 144,
      "impact": 1,
      "start_date": "2024-03-26 07:34",
      "text": "Incident",
      "updates": [
        {
          "status": "resolved",
          "text": "The services were checked and the metrics show no errors. The healthbars stayed green the whole time. ",
          "timestamp": "2024-03-26 08:38"
        }
      ]
    }
  ],
  "name": "Virtual Private Network"
}
```
